export const SERVICIOS = [
  {
    id: "marquesinas",
    label: "Marquesinas",
    group: "carteles",
    desc: "Fabricadas en caño estructural, con frentes en lona impresa, chapa galvanizada o Alucobond según la medida reglamentaria.",
    material: "Caño estructural + lona, chapa galvanizada o Alucobond",
    iluminacion: "Opcional, con letras corpóreas iluminadas o no",
    durabilidad: "Alta (exterior)",
    fabricacion: "A definir según proyecto",
    idealPara: "Frentes comerciales y franquicias",
  },
  {
    id: "letras-corporeas",
    label: "Letras Corpóreas",
    group: "carteles",
    desc: "Para interior en polyfan, MDF y acrílico. Para exterior, chapa, acero y acrílico. Fabricadas según la identidad de cada marca.",
    material: "Polyfan, MDF, acrílico, chapa o acero",
    iluminacion: "Opcional, iluminadas o no",
    durabilidad: "Alta",
    fabricacion: "A definir según proyecto",
    idealPara: "Fachadas, recepciones e interiores",
  },
  {
    id: "chapa-alucobond",
    label: "Chapa y Alucobond",
    group: "carteles",
    desc: "Carteles forrados en placa de Alucobond o chapa galvanizada, routeados o con letras corpóreas y carteles termoformados aplicados.",
    material: "Alucobond o chapa galvanizada",
    iluminacion: "Según diseño",
    durabilidad: "Muy alta (exterior)",
    fabricacion: "A definir según proyecto",
    idealPara: "Grandes fachadas y revestimientos",
  },
  {
    id: "backlight-frontlight",
    label: "Backlight y Frontlight",
    group: "carteles",
    desc: "Backlight con doble estructura y tapa perimetral en chapa, iluminados por dentro. Frontlight en caño estructural con lona impresa, iluminados por reflectores.",
    material: "Estructura metálica + lona impresa",
    iluminacion: "LED interior (backlight) o reflectores (frontlight)",
    durabilidad: "Alta",
    fabricacion: "A definir según proyecto",
    idealPara: "Cartelería de gran impacto nocturno",
  },
  {
    id: "senaletica-vinilo",
    label: "Señalética y Vinilo",
    group: "grafica",
    desc: "Carteles de señalética en materiales aptos para interior y exterior, con gráfica en vinilo de corte o impreso. Ploteo de vidrieras, paneles y vehículos.",
    material: "Vinilo de corte o impreso",
    iluminacion: "No aplica",
    durabilidad: "Alta (2–5 años en exterior)",
    fabricacion: "A definir según proyecto",
    idealPara: "Vidrieras, oficinas y gráfica vehicular",
  },
  {
    id: "banners-gigantografias",
    label: "Banners y Gigantografías",
    group: "grafica",
    desc: "Impresiones de gran formato para eventos, locales y vía pública.",
    material: "Lona o vinilo impreso de gran formato",
    iluminacion: "No aplica",
    durabilidad: "Media (según exposición)",
    fabricacion: "A definir según proyecto",
    idealPara: "Eventos, promociones y vía pública",
  },
  {
    id: "trabajos-especiales",
    label: "Trabajos Especiales",
    group: "grafica",
    desc: "Piezas de diseño a medida para proyectos que exigen una solución distinta a lo estándar.",
    material: "Combinado, a medida",
    iluminacion: "Según diseño",
    durabilidad: "Alta",
    fabricacion: "A definir según proyecto",
    idealPara: "Proyectos con identidad particular",
  },
];

export const GROUPS = [
  { id: "carteles", label: "Carteles" },
  { id: "grafica", label: "Gráfica" },
];

export const getServicio = (id) => SERVICIOS.find((s) => s.id === id);
